Added route to check google token and reg new user
siyoga/pay-with-crypto pull request #50
Opened 2023-08-17 18:36 UTC by Krenras

Докинул ручку для теста гугловского токена и дальнейшей регистрации нового пользователя внутри сиситемы.

Скрин с подтверждением:
![image](https://github.com/siyoga/pay-with-crypto/assets/81973532/a281a7a8-5307-46a7-ba36-e9538e425c23)

2023-08-17 18:36 UTC, Krenras commented
А, ну и удалил нахрен тесты...

2023-08-19 13:15 UTC, siyoga requested changes

2023-08-19 13:15 UTC, siyoga commented on app/handlers/auth.handler.go
> +	}
Эти два сейва можно передвинуть друг к другу. Инитишь пользователя, создаешь рефреш - сохраняешь две структуры

2023-08-19 13:15 UTC, siyoga commented on app/controllers/auth.controller.go
> +	route.Post("/google/tokeninfo", handlers.TokenInfo)
Переименуй в /google/register, пожалуйста

2023-08-19 13:15 UTC, siyoga commented on app/controllers/auth.controller.go
> +	route.Post("/google/tokeninfo", handlers.TokenInfo)
старый роут google/register и google/callback можно удалить, и их логику тоже

2023-08-19 17:06 UTC, Krenras commented on app/handlers/auth.handler.go
> +	}
Подругому нельзя

2023-08-19 17:06 UTC, Krenras commented on app/handlers/auth.handler.go
> +	}
По другому не работает

2023-08-19 17:07 UTC, siyoga commented on app/handlers/auth.handler.go
> +	}
А, да, я понял. Мой затуп

2023-08-19 17:11 UTC, siyoga approved these changes
Спасибо

2023-08-19 17:11 UTC, merged